### ISSUE TITLE
Data Stress-Strain untuk HVS dan Mika

### ISSUE THREAD

**Issue by AngeliFransiskaNjo** [dudung/datasets#3]
I would like to submit dataset with following information

- feature : Stress, strain
- material : HVS
- metadata: `HVS_5.json`

```json
{
"creator": "Angeli",
"date": "2024-04-03 00:00",
"material": "HVS",
"specimen": 1,
"editor": "Angeli",
"update": "2024-04-17 23:12",
"delimiter": "comma",
"column": ["Stress", "Strain"],
"type": ["float", "float"],
"unit": ["N", "mm^2"],
"data": "[HVS_5.csv]"
}
```

- file: 
[HVS_5.csv](https://github.com/dudung/datasets/files/15015002/HVS_5.csv)

**Comment by dudung** [comment]
Thank you, @AngeliFransiskaNjo. Is this still the previous data that you want to correct the paper thickness?

**Comment by dudung** [comment]
+ As seen from https://github.com/AngeliFransiskaNjo/datasets/tree/main/data/Stess_Strain_HVS
![image](https://github.com/dudung/datasets/assets/7240685/4e1e2a1d-b434-4a15-a107-cb28273530ce)
+ You should fetch upstream first (due to 11 commits behind the main repo.)
+ Then you should create a pull request (due to 2 commits ahead the main repot).
+ You can text me for further assistance about those above.
