### ISSUE TITLE
Data COVID WHO

### ISSUE THREAD

**Issue by sevinurafni** [dudung/datasets#4]
Pak, I have tried to push covid data. The data summarizes confirmed cases from the [WHO COVID-19 situation report](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/). 

 I forgot and haven't found a source that summarizes this data. I will add when I find it.

[who_covid_19_sit_rep_time_series.csv](https://github.com/dudung/datasets/files/15058489/who_covid_19_sit_rep_time_series.csv)

**Comment by dudung** [comment]
+ From https://github.com/sevinurafni/datasets/tree/main/data/covid it seems that the JSON file is still missing.
+ You should synchronize it first
![image](https://github.com/dudung/datasets/assets/7240685/26a8f833-a786-4ea9-924d-38eb3ef2f5c9)
+ Fetch upstream to have the update (since it is 2 commits behind).
+ Then create pull request to add your update to main repo after completing the CSV file (since it is 1 commit ahead).

**Comment by sevinurafni** [comment]
Yes, Pak. I missed the pull request part.
I have a pull request, please check.

**Comment by dudung** [comment]
+ @sevinurafni, please correct the JSON file.
+ It is not the dataset in other format but about the dataset.
